[package]
name = "charter"
version = "1.0.0-alpha.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.25", features = ["derive"] }
ctrlc = "3.4.5"
hex = "0.4.3"
plotters = "0.3.7"
serialport = "4.6.1"
