[package]
name = "charter"
version = "1.0.0-alpha.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.25", features = ["derive"] }
ctrlc = "3.4.5"
hex = "0.4.3"
serialport = "4.6.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
